### ISSUE TITLE
Documentation on training and predicting

### ISSUE THREAD

**Issue by ghost** [fengxinjie/Transformer-OCR#3]
@fengxinjie Thank you for your hard work,

- Put further documentation on training and predicting icdar2015
- Can Transformer-OCR be trained to detect entire text-lines instead of words?

**Comment by ghost** [comment]
@zobeirraisi
- how did you train a new icdar2015 model
- what did you change in `train.py`
- what should i replace `your-train-lines` in `train.py` with

**Comment by ghost** [comment]
> what should i replace your-train-lines in train.py with

This is path to txt file containing the image paths and corresponding labels.

**Comment by ghost** [comment]
@Anon1725 sample training data

**Comment by gussmith** [comment]
Using the previously uploaded pretrained model: IC1500 or IC1501, 
which I assumed was for ICDAR15 data, with: 
`model.load_state_dict(torch.load('IC1500'))
`
I get the following errors: 
with IC1500: 

`python predict.py `

``` 
Traceback (most recent call last):
  File "predict.py", line 12, in <module>
    model.load_state_dict(torch.load('IC1500'))
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 585, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 245, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:143] . PytorchStreamReader failed reading zip archive: failed finding central directory
```
and with IC1501: 
```
Traceback (most recent call last):
  File "predict.py", line 12, in <module>
    model.load_state_dict(torch.load('IC1501'))
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 592, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xb7'.
```
Any suggestion on how to run with the pre-trained files provided?

**Comment by gussmith** [comment]
Answering my own question above: 
@deepseek provided the answer in a resolved issue: 
> ```
> cd checkpoints && cat IC1500 IC1501 > IC15.zip && unzip IC15.zip
> ```

**Comment by rjadr** [comment]
Better documentation on training and predicting is seriously needed. I ran this script on colab and am not able to ocr even the most straightforward texts accurately: [https://colab.research.google.com/gist/rjadr/0f0a9eb5d3a3660ce2f52df002503462/transformer-ocr.ipynb](https://colab.research.google.com/gist/rjadr/0f0a9eb5d3a3660ce2f52df002503462/transformer-ocr.ipynb)

**Comment by gussmith** [comment]
@rjadr Following your colab, if I understand correctly, you get the text "LEXI" at the output?

**Comment by gussmith** [comment]
@rjadr 
I think you have to change this line to: True, in model.py
`resnet = getattr(models, 'resnet101')(pretrained=False)`

**Comment by rjadr** [comment]
@gussmith yes it outputs "LEXI", not quite the result I was hoping for. Other simple examples give similar misrepresentations.

**Comment by gussmith** [comment]
@fengxinjie 
The vocab provided in the code: 
`vocab =  "<,.+:-?$ 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ>"`
does not cover all the symbols in the ICDAR 2015 Word Recognition.  
A set that covers all the symbols is more like: 
`vocab =  "<=,.+:;-!?$%#&*' ()@éÉ/\[]0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ>"+'"'+"´"+"΅"`

Note that all these symbols had to be added: 
`"%#&*' ()@éÉ/\[]" +'"'+"´"+"΅"`
That is 16 or 17 added symbols are needed (the symbol after * may have been repeated at the end). 
Thus I suspect that the vocab in the code is not the vocab used to train the IC15.pth , but rather another dataset. 
One would not expect a top performance if the vocab does not even cover all the symbols in the dataset. 
Note how `token2char` is needed in predict.py, thus the wrong vocab will give the wrong prediction. 

In addition, in order to read the original IC15 dataset, the original code must be changed to: 
```
           # lines = open(f).readlines()
           # self.lines += [i for i in lines if not illegal(i.strip('\n').split('\t')[1])]  
            lines = open(f,encoding='utf-8-sig').readlines()
            self.lines += [i for i in lines if not illegal(i.strip('\n').split(', ')[1].strip('"'))]
```
where the original is commented out and the `encoding='utf-8-sig'` is needed to remove a hidden character at the beginning of the file.

Thus, the code provided does not appear to be for the IC15 dataset, and potentially why the author removed the pretrained model (?).

**Comment by gussmith** [comment]
The predict.py code also resize the input image to `SIZE=96`, one would need to check that the input image still has the text info after that process.

**Comment by gussmith** [comment]
> @gussmith yes it outputs "LEXI", not quite the result I was hoping for. Other simple examples give similar misrepresentations.

See issues: 
testloss would lead to model update on eval mode #7
Why the recognition accuracy different from paper? #4

It seems to overfit the data, and may not work so well on new data.
